<?php
// auto-generated by sfPropelCrud
// date: 2015/08/04 22:32:19
?>
<?php use_helper('Object') ?>

<?php echo form_tag('user/update') ?>

<?php echo object_input_hidden_tag($user, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Nickname:</th>
  <td><?php echo object_input_tag($user, 'getNickname', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>First name:</th>
  <td><?php echo object_input_tag($user, 'getFirstName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Last name:</th>
  <td><?php echo object_input_tag($user, 'getLastName', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($user->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'user/delete?id='.$user->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'user/show?id='.$user->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'user/list') ?>
<?php endif; ?>
</form>
