<?php
// auto-generated by sfPropelCrud
// date: 2015/08/04 22:32:19
?>
<h1>user</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Nickname</th>
  <th>First name</th>
  <th>Last name</th>
  <th>Created at</th>
</tr>
</thead>
<tbody>
<?php foreach ($users as $user): ?>
<tr>
    <td><?php echo link_to($user->getId(), 'user/show?id='.$user->getId()) ?></td>
      <td><?php echo $user->getNickname() ?></td>
      <td><?php echo $user->getFirstName() ?></td>
      <td><?php echo $user->getLastName() ?></td>
      <td><?php echo $user->getCreatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'user/create') ?>
