<?php
// auto-generated by sfPropelCrud
// date: 2015/08/04 22:32:19
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $user->getId() ?></td>
</tr>
<tr>
<th>Nickname: </th>
<td><?php echo $user->getNickname() ?></td>
</tr>
<tr>
<th>First name: </th>
<td><?php echo $user->getFirstName() ?></td>
</tr>
<tr>
<th>Last name: </th>
<td><?php echo $user->getLastName() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $user->getCreatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'user/edit?id='.$user->getId()) ?>
&nbsp;<?php echo link_to('list', 'user/list') ?>
