<?php
// auto-generated by sfPropelCrud
// date: 2015/08/04 22:32:20
?>

<?php use_helper('Text') ?>
 
<h1>popular questions</h1> 
 
<?php echo include_partial('list', array('question_pager' => $question_pager, 'rule' => 'question/list' )) ?>
